### ISSUE TITLE
Add an option to show the name of the deck in rich presence

### ISSUE THREAD

**Issue by azunagi** [STadas/Ankicord#1]
I'd like to show which deck I'm working on. I think people should have the option to enable or disable this option since not everyone wants to show the names of their decks.

**Comment by STadas** [comment]
I've actually considered adding that and tried looking for ways to do it but couldn't find any after some searching. I'll look into it once more when I have some time though!

**Comment by STadas** [comment]
e527382dd9f3b596b5747ede006dd3887280b886
