### ISSUE TITLE
Support for versions under 2.149?

### ISSUE THREAD

**Issue by evkaw** [STadas/Ankicord#14]
Hey, Idk if this is of interest to anyone but I would really like if this add-on worked with versions below 2.149. I use 2.135 & I cannot use it and can't find another that has the same functionality. Thanks for the help!

**Comment by STadas** [comment]
Hi, sorry but I don't plan on supporting earlier versions because juggling the breaking changes between multiple Anki versions is a bit of a hassle. If you want to, you can try downloading one of the [earlier releases](https://github.com/STadas/Ankicord/releases) of the add-on and see if they work!
