### ISSUE TITLE
Enhancement: Option to update more frequently 

### ISSUE THREAD

**Issue by akavi1** [STadas/Ankicord#15]
Hi, thanks for making this, I was using the AnkiDiscord addon for some time now, but I'm switching over to this one because it seems to be better in almost every way.

Is there a reason why the status is limited to update only every 15 seconds? Would it be possible to make a config option to allow more frequent status updates?  I manually changed it in main.py to update every 5 sec for now but I assume those changes will be overwritten next time this addon gets updated. Thanks.

**Comment by STadas** [comment]
Hi, unfortunately as far as I know 15 seconds is the minimum delay Discord would like people to use. If you try to update it more frequently, the updates will start to queue up instead and later ones will end up being really slow. I imagine that makes it easier for them to balance loads on their servers.
