### ISSUE TITLE
Error when interacting with UI (Decks, Add, Browse, Stats, Sync)

### ISSUE THREAD

**Issue by gnitsetb125** [STadas/Ankicord#16]
**General info (please complete the following information):**
 - OS: [Windows 10]
 - Anki version [2.1.49]
 - Any errors? [Yes, copy-paste of error below]
 - Have you restarted Anki after installing the add-on? [Yes]

**Describe the bug**
When clicking on the top buttons (Decks, Add, Browse, Stats, Sync), this error pops up.

Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-04-10 21:28:39

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022411123C10>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 115, in __del__
  File "asyncio\proactor_events.py", line 79, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by STadas** [comment]
Hi, can you check if the error persists when the addon is turned off as well? I can't seem to reproduce this.

**Comment by gnitsetb125** [comment]
> Hi, can you check if the error persists when the addon is turned off as well? I can't seem to reproduce this.

Uploading 2022-04-11 14-41-53.mp4…

The error does not persist when the addon is turned off.

**Comment by gnitsetb125** [comment]
> Hi, can you check if the error persists when the addon is turned off as well? I can't seem to reproduce this.

The error does not persist when the addon is turned off.

https://user-images.githubusercontent.com/103417573/162857862-40f64454-a1dc-490d-95d1-ed5d56353315.mp4

**Comment by STadas** [comment]
Honestly, at the moment I'm not sure what's causing the issue. I noticed that your python version is 3.8.6 so I do wonder if that's something to look into, as [this suggests](https://github.com/ankitects/anki/blob/main/docs/development.md) that you **might** need 3.9, though again I'm not sure how important that is. I'm not a Windows user so it's a bit difficult for me to test this, so I will probably get back to it once I'm a bit less busy with university.

If anyone else encounters this or finds out something about the problem, please let me know in this issue, thanks!
