### ISSUE TITLE
since new update anki crashing and incorrect discord activity

### ISSUE THREAD

**Issue by Minethatcoin** [STadas/Ankicord#18]
![image](https://user-images.githubusercontent.com/35110284/163691126-f97b3455-7812-41d6-b402-77df5610776d.png)

yeah ever since i got the prompt for the update to ankicord my anki has crashed twice on startup of application and all it says as my discord activity is that I've been playing anki for (x) mins. that's aboutit . it was working perfectly fine previously

**Comment by STadas** [comment]
Please use the template to make an issue about a bug
