### ISSUE TITLE
No effect after installation (Linux)

### ISSUE THREAD

**Issue by luni3359** [STadas/Ankicord#21]
**General info (please complete the following information):**
 - OS: KDE Neon 20.04 (based on Ubuntu 20.04)
 - Anki version 2.1.51 (cf78a555)⁩
 - Any errors? No
 - Have you restarted Anki after installing the add-on? Yes

**Describe the bug**
I'm sorry I can't say much but I'm just not seeing anything happen when the addon is installed. Please let me know what information I can provide if it used to work on Linux.

**Comment by STadas** [comment]
Hmm, I guess we can start with whether your Activity Status is turned on in Discord?
![image](https://user-images.githubusercontent.com/43136162/166875692-cc0d55d7-8690-4c70-a33a-74a110fa823b.png)

**Comment by luni3359** [comment]
Sorry I forgot to mention that but that's also active.

**Comment by STadas** [comment]
Could you try launching anki from the terminal and see if anything pops up? There should be some output on errors.

**Comment by luni3359** [comment]
I feel so dumb... I'm getting the status now, but I don't know what fixed it.

Thanks for your help, and I apologize for the trouble.
