### ISSUE TITLE
Anki Keeps Insisting New Update Available After Install

### ISSUE THREAD

**Issue by Kosezu** [STadas/Ankicord#28]
**General info (please complete the following information):**
 - OS: [e.g. Windows 10] MacOS Ventura 13.5
 - Anki version [e.g. 2.1.44] 2.1.65
 - Any errors? [No / screenshot or copy-paste of error] No errors
 - Have you restarted Anki after installing the add-on? [Yes / No] Yes

**Describe the bug**

After the latest update, every time I check for updates in Anki, this add-on pops up as having an available update (latest 8/15/2023 update). Installing the updates does nothing it appears, and I am prompted to install the update again once I check for updates. On latest public Anki 65, MacOS.

**Comment by STadas** [comment]
I could reproduce the issue and it seems that I might've messed up while updating the add-on on Ankiweb. Reuploading it seems to have fixed it. If the issue is still there for you, please reopen the ticket
