### ISSUE TITLE
Count only most recent deck - not working?

### ISSUE THREAD

**Issue by tdlab** [STadas/Ankicord#29]
Hi, I love the addon and just wanted to post a bug that I am having.

I have my main anki deck that i keep up with daily, and then a secondary 'burner' anki deck that I kinda/sorta/should really do. 
I have count_deck set to 'yes', however it seems to still sum up all of my unsuspended cards, rather than just my last deck, as you can see in the screenshots below. It should be only registering the latest deck, the Anking Overhaul deck.
![image](https://github.com/STadas/Ankicord/assets/5712783/a2b142d6-c1a3-42c7-aa6a-673e0f13ac62)
![image](https://github.com/STadas/Ankicord/assets/5712783/d8ad1de7-7516-4bff-9b46-b5f9f5870ec0)
![image](https://github.com/STadas/Ankicord/assets/5712783/f46475f5-4d73-4084-8542-0fe6790cee3f)

Am I doing something wrong, or is there some sort of bug that I am happy to help troubleshoot

**Comment by tdlab** [comment]
OS: Windows 11?
Anki version Version ⁨2.1.63 v3 scheduler
Any errors? No
Have you restarted Anki after installing the add-on? Yes

**Comment by STadas** [comment]
I can't seem to reproduce this. Are you sure the count persistently stays at that high number even 15 seconds after starting to study the deck? For reference, the addon updates the count and status exactly every 15 seconds.

**Comment by STadas** [comment]
Oh, I've just realised that you've set the value of `"count_deck"` to `"yes"`. It should instead be `"on"`, like the other settings. I should really just make all of them `true`/`false` to avoid confusion... Perhaps some day when I'm not too lazy to rewrite the thing
