### ISSUE TITLE
show cards left for currently active deck instead of all decks

### ISSUE THREAD

**Issue by agaertner** [STadas/Ankicord#3]
Thanks for taking this on.

I generally have a problem with both addons including the old.

Both count the total cards **in each deck**.

but some of my decks I have are inactive and not on my study list.

It would be much much better if it just took the values that are in the current active deck that is being studied until it says "Congratulation, this deck is finished for today".

as for the current implementation I cannot use the card_count setting because it shows a value of almost 8000 cards left which is rather misleading.

**Comment by STadas** [comment]
That's fair enough. It shouldn't be too difficult to implement, I'll have a look once I'm not as busy with uni. Thanks for the feedback :)

**Comment by agaertner** [comment]
Thanks :)

First you could try to show the cards left in the active study deck.

After that's working you could also make a setting and show review_count which is indicated by the blue, red, green numbers at the bottom of an active deck that is studied.

> When only the question is shown, Anki shows three numbers like 12 + 34 + 56 at the bottom of the screen. These represent the new cards, cards in learning, and cards to review. If you’d prefer not to see the numbers, you can turn them off in Anki’s  preferences. Note
The numbers count reviews needed to finish all the cards in that queue, not the number of cards. If you have multiple steps  configured for lapsed cards, the number will increase by more than one when you fail a card, since that card needs to be shown several times.  

source: https://apps.ankiweb.net/docs/manual20.html#due-counts-and-time-estimates

**Comment by agaertner** [comment]
Hey gj however. I think you confused something.

blue + red + green
16 + 1 + 0

will result in your plugin showing "No cards left" I tried with other scenarios. It appears to always show No cards left.

**Comment by STadas** [comment]
hmmm could you paste your config here?

**Comment by agaertner** [comment]
```
{
    "defaults": {
        "main": {
            "activity": "on",
            "card_count": "on",
            "count_deck": "on",
            "deck_name": "on",
            "spotify": "off",
            "timer": "on"
        },
        "statuses": {
            "browsing_status": "Browsing decks",
            "editing_status": "Adding cards",
            "menu_status": "Slacking off",
            "no_cards_left_txt": "No cards left",
            "reviewing_status": "Daily reviews"
        }
    }
}
```

**Comment by STadas** [comment]
Ah I see. You need to reset your config back to default, which will add some new options. I should probably add some backwards-compatibility though to mitigate this anyway. Thank you!

**Comment by STadas** [comment]
I've opened a new issue for the bug so I'll close this for now
