### ISSUE TITLE
windows 11

### ISSUE THREAD

**Issue by nin0o0** [STadas/Ankicord#30]
**General info (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Anki version [e.g. 2.1.44]
 - Any errors? [No / screenshot or copy-paste of error]
 - Have you restarted Anki after installing the add-on? [Yes / No]

**Describe the bug**

**Comment by STadas** [comment]
Not sure I understand a point of this ticket. Please use the form if there's a problem you've encountered with the addon.
