### ISSUE TITLE
Add-on not working

### ISSUE THREAD

**Issue by AmariCelia** [STadas/Ankicord#8]
I downloaded the add-on, but for some reason, it is still not working. Do I have to enable something specific on Discord?

**Comment by STadas** [comment]
Hi, which anki version are you using? Have you restarted anki after installing the add-on?

**Comment by AmariCelia** [comment]
I'm using the latest version (2.1.43). I tried restarting Anki multiple times, as well as disable and then enabling it again.

**Comment by STadas** [comment]
I'm guessing you didn't change anything in the config but could you post it just in case as well?

**Comment by AmariCelia** [comment]
Oh never mind. I just had to restart my PC and now it's working. Thanks anyway and I really appreciate your quick response :)

**Comment by STadas** [comment]
Whew, got me worried there, I thought they completely dropped some function's support or something in the recent update. No worries though haha glad it works!
